### ISSUE TITLE
No login possible

### ISSUE THREAD

**Issue by SirTom76** [schild-report/schild.report#5]
Ich habe das msi Paket von schild.report installiert und eine Verbindung zu unserer mysql Datenbank hergestellt. Leider kann ich mich aber nicht über unsere Schild Zugangsdaten einloggen. Es erscheint immer ein Fehler, dass die Benutzerdaten ungültig sind.

Wo lassen sich die Datenbank-Einstellungen im Nachhinein ändern?

**Comment by hmt** [comment]
Starte mal bitte über die Kommandozeile: `schild.report.exe --devtools`. Damit haben wir die Developer Tools und können aus der Konsole etwas mehr erfahren.
Wie weit kommst Du? Du hast die Zugangsdaten eingestellt auf ok geklickt und konntest Dich nicht anmelden? Es kann sein, dass ein einfacher Neustart ausreicht, u.U. sind die Verbindungsdaten dann nicht im Loginfenster verfügbar und das wäre ein Fehler, den ich dann beheben müsste.

**Comment by SirTom76** [comment]
Die Fehlermeldung ist etwas merkwürdig, die Tabelle users wird nicht gefunden...

DBError: select `users`.* from `users` where `US_LoginName` = 'hat' - ER_NO_SUCH_TABLE: Table '**********.users' doesn't exist
    at wrapError (C:\Users\**********\AppData\Local\Programs\schild.report\resources\app.asar\node_modules\db-errors\lib\dbErrors.js:19:14)
    at handleExecuteError (C:\Users\**********\AppData\Local\Programs\schild.report\resources\app.asar\node_modules\objection\lib\queryBuilder\QueryBuilder.js:1489:32)
    at QueryBuilder.execute (C:\Users\**********\AppData\Local\Programs\schild.report\resources\app.asar\node_modules\objection\lib\queryBuilder\QueryBuilder.js:670:20)
    at async Schild.getNutzer (file:///C:/Users/**********/AppData/Local/Programs/schild.report/resources/app.asar/build/schild_worker.js:424:19)
 
Die Tabelle ist aber definitiv da. Gibt es eine Möglichkeit, die Datenbankverbindung anzuapssen? Ich habe noch eine lokale DB, mit der ich das nochmal testen könnte.

**Comment by hmt** [comment]
Du müsstest die config-Datei löschen. Wo die auf Windows ist, weiß ich leider nicht auswendig. Es gibt ein Datenverzeichnis, wo alle Programme ihre Sachen wie Konfiguration etc ablegen können. Dort existiert auch ein schild.report-Ordner mit der `config.json`. Die kann gelöscht werden, dann muss man automatisch alle Daten neu eingeben. Hast Du womöglich die falsche Datenbank angegeben, wo keine users Tabelle drin ist? Das wäre ein Grund, die Verbindung herzustellen und dann trotzdem zu scheitern.

**Comment by hmt** [comment]
Können wir den Punkt zumachen? Hat sich die Frage geklärt?
